"""add detailed cost fields to usage model

Revision ID: 63ce91c8539c
Revises: 5837c40838ff
Create Date: 2025-01-07 22:13:16.723179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63ce91c8539c'
down_revision = '5837c40838ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('output_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=True))
        batch_op.drop_column('cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.FLOAT(), nullable=True))
        batch_op.drop_column('total_cost')
        batch_op.drop_column('output_cost')
        batch_op.drop_column('input_cost')

    # ### end Alembic commands ###
